#!/usr/bin/env php
<?php
/**
 *  @file:   console.php
 *  @brief:  人口文件
 *  @date:   2015-10-28
**/

define('THIS_PATH',     __DIR__ .'/');
define('APP_NAME',      'console');

require(THIS_PATH .'env.php');
require(VENDOR_PATH . 'autoload.php');
require(VENDOR_PATH . 'yiisoft/yii2/Yii.php');
require(APP_PATH . 'config/alias.php');

$config = yii\helpers\ArrayHelper::merge(
    require(APP_PATH . 'config/main.php'),
    require(APP_PATH . APP_NAME .'/config/main.php')
);

$application = new yii\console\Application($config);
exit($application->run());
